spring:
  main:
    banner-mode: off
  application:
    name: SystemApiApplication
  profiles:
    active: dev
  freemarker:
    check-template-location: false
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  #配置 Jpa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 解决 FetchType.LAZY 失效问题 的问题，如果没这个句话，所有关联都要加FetchType.EAGER 例如：@ManyToMany(fetch=FetchType.EAGER)
        enable_lazy_load_no_trans: true
        # postgres配置
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        #mysql依赖
        #dialect: org.hibernate.dialect.MySQL8Dialect
        session_factory:
          statement_inspector: com.remember5.system.intercepter.MyIntercepter

    open-in-view: true

# 内存用户缓存配置
user-cache:
  # 最小回收数(当缓存数量达到此值时进行回收)
  min-evictable-size: 512
  # 最小回收间隔
  min-evictable-interval: 1800000
  # 最小存活时间 (ms)
  min-idle-time: 3600000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.remember5.system
  global-config:
    banner: off
    # 数据库相关配置
    db-config:
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
