server:
  port: 8000
#配置数据源
spring:
  autoconfigure:
    # 排除 Druid 自动配置
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    # 指定使用 Druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      strict: false
      datasource:
        # 主库数据源
        master:
          driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://118.25.95.207:3306/eladmin_template?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
          username: eladmin_template
          password: EladminTemplate@2021
        # 从库数据源
    #        slave:
    #          driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #          url: jdbc:log4jdbc:mysql://129.28.xx.xx:2000/xx?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    #          username: root
    #          password: .
    druid:
#      db-type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      url: jdbc:log4jdbc:mysql://118.25.95.207:3306/eladmin_template?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      username: eladmin_template
#      password: EladminTemplate@2021
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 15
      # 最大连接数
      max-active: 30
      # 超时时间(以秒数为单位)
      remove-abandoned-timeout: 180
      # 获取连接超时时间
      max-wait: 3000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis
  redis:
    #数据库索引
    database: 9
    host: 118.25.95.207
    port: 6379
    password: lQrVBDbu9rR7T3oY
    #连接超时时间
    timeout: 5000

# 登录相关配置
login:
  # 登录缓存
  cache-enable: true
  #  是否限制单用户登录
  single-login: false
  #  验证码
  captcha-code:
    #  验证码类型配置 查看 LoginProperties 类
    type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体，如遇到线上乱码，设置其他字体即可
    font-name:
    # 字体大小
    font-size: 25

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000
  # 放行接口
  permit:
    defaults-url:
      - "/swagger-ui.html" # swagger 文档
      - "/swagger-resources/**"
      - "/webjars/**"
      - "/*/api-docs"
      - "/avatar/**" # 文件
      - "/file/**"
      - "/druid/**" # 阿里巴巴 druid
    get-url:
      - "/*.html"
      - "/**/*.html"
      - "/**/*.css"
      - "/**/*.js"
      - "/webSocket/**"
      - "/ws/**"
    post-url:
    put-url:
    delete-url:

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

# IP 本地解析
ip:
  local-parsing: true

# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/eladmin/file/
    avatar: /home/eladmin/avatar/
  windows:
    path: C:\eladmin\file\
    avatar: C:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

user:
  # 大汉接口配置
  information:
    account: dh94732
    password: 7S4hNeHg

#是否开启 swagger-ui
swagger:
  enabled: true
  title: 'eladmin-nt1模版项目'
  description: '后台管理接口文档'
  author: '王家豪'
  email: '1332661444@qq.com'
  blog: 'https://blog.remember5.top'
  service-url: 'http://127.0.0.1:8080'
  version: '1.0'
  host: '/'
  group-name: 后台管理
  base-package: me.zhengjie


# TODO 要给prod环境也加上配置
knife4j:
  enable: true
  cors: false
  production: false
  basic:
    enable: false
    username: test
    password: 12313
  documents:
    -
      group: 2.X版本
      name: 接口签名
      locations: classpath:sign/*
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: true
    enableHost: false
    enableHostText: 192.168.0.193:8000
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableSearch: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2019-[浙江八一菜刀股份有限公司](https://gitee.com/xiaoym/knife4j)
    enableDynamicParameter: false
    enableDebug: true
    enableOpenApi: false
    enableGroup: true


