# 使用docker才需要，如果是本机运行，建议注释
image: docker:20.10.18
# 本次构建的阶段：build package
stages:
  - build
  - deploy

# 全局环境变量
variables:
  MY_NAME: ""

# 导入单个模版
include:
  - local: .gitlab/ci/*.gitlab-ci.yml
#  - remote: 'https://gitlab.com/gitlab-org/frontend/untamper-my-lockfile/-/raw/main/.gitlab-ci-template.yml'
