# 本次构建的阶段：build package
stages:
  - compile
  - test
  - package
  - dock


# 全局环境变量
variables:
  MY_NAME1: "wangjiahao"


# 导入单个模版
include:
  - local: .gitlab/ci/*.gitlab-ci.yml
#  - remote: 'https://gitlab.com/gitlab-org/frontend/untamper-my-lockfile/-/raw/main/.gitlab-ci-template.yml'
