spring:
  main:
    banner-mode: off
  application:
    name: OpenApiApplication
  profiles:
    active: dev
  freemarker:
    check-template-location: false
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.remember5.openapi.modules.*.mapper, com.remember5.biz.*.mapper
  global-config:
    banner: off
    # 数据库相关配置
    db-config:
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      logic-delete-field: isDeleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 原生配置
  configuration:
    cache-enabled: false # 关闭二级缓存
    local-cache-scope: STATEMENT # https://baomidou.com/pages/56bac0/#localcachescope
