# =========== 开发环境 ===========

# 环境变量
variables:
  DB_HOST:
  DB_PORT:
  DB_NAME:
  DB_USER:
  DB_PWD:
  REDIS_HOST:
  REDIS_PORT:
  REDIS_PWD:
  REDIS_DB:
  DRUID_USER:
  DRUID_PWD:

# 开发环境啥也不干
dev-build:
  stage: compile
  script:
    - echo "=============== $MY_NAME ==============="
  only:
    - dev