# =========== 测试环境 ===========

# 环境变量
variables:
  DB_HOST:
  DB_PORT:
  DB_NAME:
  DB_USER:
  DB_PWD:
  REDIS_HOST:
  REDIS_PORT:
  REDIS_PWD:
  REDIS_DB:
  DRUID_USER:
  DRUID_PWD:

# 构建 Job
test-build:
  stage: compile
  script:
    - echo "=============== 开始编译构建任务 ==============="
    - $MAVEN_HOME/bin/mvn compile
  only:
    - test
